name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v2
      with:
        path: path/to/artifact/world.txt
    - name: Store the current date and time
      id: date_time
      run: echo "::set-output name=date_time::$(date '+%Y%m%d-%H%M%S')"
    - name: Compute short SHA of the commit
      id: sha_short
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Add release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.REPO_ACCESS_TOKEN }}"
        automatic_release_tag: "release-${{ steps.date_time.outputs.date_time }}-${{ steps.sha_short.outputs.sha_short }}"
        prerelease: true
        title: "Release ${{ steps.date_time.outputs.date_time }} ${{ steps.sha_short.outputs.sha_short }}"
        files: |
          path/to/artifact/*
    - uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 3
        delete_tag_pattern: release
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
